-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 15:24:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(255) NULL,
                                              `img` TEXT NULL,
                                              PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `country` VARCHAR(45) NULL,
                                                 `city` VARCHAR(45) NULL,
                                                 `img` TEXT NULL,
                                                 `movie_id` INT NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 INDEX `fk_location_movie_idx` (`movie_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_location_movie`
                                                     FOREIGN KEY (`movie_id`)
                                                         REFERENCES `mydb`.`movie` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`package` ;

CREATE TABLE IF NOT EXISTS `mydb`.`package` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `hotel_name` VARCHAR(255) NULL,
                                                `inclusive` TINYINT NULL,
                                                `price` INT NULL,
                                                `activities` VARCHAR(255) NULL,
                                                `location_id` INT NULL,
                                                PRIMARY KEY (`id`),
                                                INDEX `fk_package_location1_idx` (`location_id` ASC) VISIBLE,
                                                CONSTRAINT `fk_package_location1`
                                                    FOREIGN KEY (`location_id`)
                                                        REFERENCES `mydb`.`location` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
